name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ssh pass
      run: sudo apt update && sudo apt install -y sshpass
    - name: Create a ssh directory
      run: mkdir ~/.ssh
    - name: Verify host via SSH
      run: ssh-keyscan 163.172.130.135 >> ~/.ssh/known_hosts
    - name: Deploy Website
      run: sshpas -p hetic scp -r /mnt/c/users/trouv/documents/projets-perso/projet-agence-de-voyage/* trouve-quentin@163.172.130.135:/home/trouve-quentin/Projet-Agence-de-Voyage
